/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getSyncSpecsSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-sync-specs',
    description: 'Sync delta specs from a change to main specs. Use when the user wants to update main specs with changes from a delta spec, without archiving the change.',
    instructions: `Sync delta specs from a change to main specs.

This is an **agent-driven** operation - you will read delta specs and directly edit main specs to apply the changes. This allows intelligent merging (e.g., adding a scenario without copying the entire requirement).

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have delta specs (under \`specs/\` directory).

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Find delta specs**

   Look for delta spec files in \`openspec/changes/<name>/specs/*/spec.md\`.

   Each delta spec file contains sections like:
   - \`## ADDED {Section}\` - New blocks to add to a section
   - \`## MODIFIED {Section}\` - Changes to existing blocks
   - \`## REMOVED {Section}\` - Blocks to remove
   - \`## RENAMED {Section}\` - Blocks to rename (FROM:/TO: format)

   If no delta specs found, inform user and stop.

3. **For each delta spec, apply changes to main specs**

   For each capability with a delta spec at \`openspec/changes/<name>/specs/<capability>/spec.md\`:

   a. **Read the delta spec** to understand the intended changes

   b. **Read the main spec** at \`openspec/specs/<capability>/spec.md\` (may not exist yet)

   c. **Apply changes intelligently**:

      **ADDED blocks:**
      - If block doesn't exist in main spec → add it to the target section
      - If block already exists → update it to match (treat as implicit MODIFIED)

      **MODIFIED blocks:**
      - Find the block in main spec by \`### Name\` heading
      - Apply the changes — update the prose content
      - Preserve content not mentioned in the delta

      **REMOVED blocks:**
      - Remove the entire \`### Name\` block from main spec

      **RENAMED blocks:**
      - Find the FROM block, rename to TO (uses \`FROM: ### Old Name\` / \`TO: ### New Name\` format)

   d. **Create new main spec** if capability doesn't exist yet:
      - Create \`openspec/specs/<capability>/spec.md\`
      - Add sections matching the ADDED section names from the delta
      - Populate with the ADDED blocks

4. **Show summary**

   After applying all changes, summarize:
   - Which capabilities were updated
   - What changes were made (requirements added/modified/removed/renamed)

**Delta Spec Format Reference**

\`\`\`markdown
## ADDED Behavior

### Two-Factor Auth
Users can enable TOTP-based two-factor authentication.
When enabled, login requires a valid TOTP code after password verification.

## MODIFIED Behavior

### Login
Updated prose describing modified behavior...

## REMOVED Behavior

### Legacy SSO

## RENAMED Behavior

FROM: ### Old Name
TO: ### New Name
\`\`\`

**Key Principle: Intelligent Merging**

Unlike programmatic merging, you can apply **partial updates**:
- To update a block, just include the changed prose under MODIFIED
- The delta represents *intent*, not a wholesale replacement
- Use your judgment to merge changes sensibly

**Output On Success**

\`\`\`
## Specs Synced: <change-name>

Updated main specs:

**<capability-1>**:
- Added block: "New Feature"
- Modified block: "Existing Feature"

**<capability-2>**:
- Created new spec file
- Added block: "Another Feature"

Main specs are now updated. The change remains active - archive when implementation is complete.
\`\`\`

**Guardrails**
- Read both delta and main specs before making changes
- Preserve existing content not mentioned in delta
- If something is unclear, ask for clarification
- Show what you're changing as you go
- The operation should be idempotent - running twice should give same result`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxSyncCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Sync',
    description: 'Sync delta specs from a change to main specs',
    category: 'Workflow',
    tags: ['workflow', 'specs', 'experimental'],
    content: `Sync delta specs from a change to main specs.

This is an **agent-driven** operation - you will read delta specs and directly edit main specs to apply the changes. This allows intelligent merging (e.g., adding a scenario without copying the entire requirement).

**Input**: Optionally specify a change name after \`/opsx:sync\` (e.g., \`/opsx:sync add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have delta specs (under \`specs/\` directory).

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Find delta specs**

   Look for delta spec files in \`openspec/changes/<name>/specs/*/spec.md\`.

   Each delta spec file contains sections like:
   - \`## ADDED {Section}\` - New blocks to add to a section
   - \`## MODIFIED {Section}\` - Changes to existing blocks
   - \`## REMOVED {Section}\` - Blocks to remove
   - \`## RENAMED {Section}\` - Blocks to rename (FROM:/TO: format)

   If no delta specs found, inform user and stop.

3. **For each delta spec, apply changes to main specs**

   For each capability with a delta spec at \`openspec/changes/<name>/specs/<capability>/spec.md\`:

   a. **Read the delta spec** to understand the intended changes

   b. **Read the main spec** at \`openspec/specs/<capability>/spec.md\` (may not exist yet)

   c. **Apply changes intelligently**:

      **ADDED blocks:**
      - If block doesn't exist in main spec → add it to the target section
      - If block already exists → update it to match (treat as implicit MODIFIED)

      **MODIFIED blocks:**
      - Find the block in main spec by \`### Name\` heading
      - Apply the changes — update the prose content
      - Preserve content not mentioned in the delta

      **REMOVED blocks:**
      - Remove the entire \`### Name\` block from main spec

      **RENAMED blocks:**
      - Find the FROM block, rename to TO (uses \`FROM: ### Old Name\` / \`TO: ### New Name\` format)

   d. **Create new main spec** if capability doesn't exist yet:
      - Create \`openspec/specs/<capability>/spec.md\`
      - Add sections matching the ADDED section names from the delta
      - Populate with the ADDED blocks

4. **Show summary**

   After applying all changes, summarize:
   - Which capabilities were updated
   - What changes were made (requirements added/modified/removed/renamed)

**Delta Spec Format Reference**

\`\`\`markdown
## ADDED Behavior

### Two-Factor Auth
Users can enable TOTP-based two-factor authentication.
When enabled, login requires a valid TOTP code after password verification.

## MODIFIED Behavior

### Login
Updated prose describing modified behavior...

## REMOVED Behavior

### Legacy SSO

## RENAMED Behavior

FROM: ### Old Name
TO: ### New Name
\`\`\`

**Key Principle: Intelligent Merging**

Unlike programmatic merging, you can apply **partial updates**:
- To update a block, just include the changed prose under MODIFIED
- The delta represents *intent*, not a wholesale replacement
- Use your judgment to merge changes sensibly

**Output On Success**

\`\`\`
## Specs Synced: <change-name>

Updated main specs:

**<capability-1>**:
- Added block: "New Feature"
- Modified block: "Existing Feature"

**<capability-2>**:
- Created new spec file
- Added block: "Another Feature"

Main specs are now updated. The change remains active - archive when implementation is complete.
\`\`\`

**Guardrails**
- Read both delta and main specs before making changes
- Preserve existing content not mentioned in delta
- If something is unclear, ask for clarification
- Show what you're changing as you go
- The operation should be idempotent - running twice should give same result`
  };
}
